#import "/template.typ": lorem

#heading(level: 1, numbering: none, outlined: true)[Abstract]

This thesis investigates the friction between reporting metrics derived from the Global North and Indigenous Knowledge Management (IKM) through a case study of Cruz Vermelha de Timor-Leste (CVTL), the Red Cross National Society in Timor-Leste.

This bureaucratization of knowledge can lead to a disconnect between the lived experiences of local humanitarian workers and the information that is being reported to donors, which can ultimately impact the effectiveness of humanitarian interventions not only through reduced responsiveness but also by undermining the trust between the local humanitarian workers and the communities they serve.

Drawing on decolonial theory, the Theory of Communicative Disenfranchisement, and the Cynefin® framework, this study employs a qualitative case study methodology. Data were gathered through semi-structured interviews with CVTL staff, Australian Red Cross program officers, a USAID representative, and an independent direct-funding practitioner, alongside document analysis of institutional reporting templates.

The findings reveal a structural domain misalignment at the core of humanitarian knowledge management: donor-mandated mechanisms---like logical frameworks (logframes), standardized indicators, and quarterly reports---are Clear-domain instruments imposed upon Complex and Chaotic humanitarian realities @CynefinUmbrex. Rather than capturing local knowledge, these systems suppress it. Local humanitarians are reduced to "custodians of comprehension" who complete forms to satisfy donor requirements, rather than "catalysts for transformation" drawing on contextual expertise @JoharCatalyst. Constant retraining sessions required to socialize staff to these tools signal the depth of the disconnect, while the administrative burden produces reporting fatigue and pressure to report outcomes that cannot be causally demonstrated.

This thesis argues that the communication chasm at CVTL reflects not an organizational anomaly but a structural incongruence rooted in colonial logics embedded in the international humanitarian system. It concludes by pointing toward complexity-informed, participatory knowledge management through the Catalyst Model built upon Sankofaist philosophy: a relationship-based, direct funding approach that catalyzes what communities already possess rather than supplanting it as pathways to an equitable humanitarianism rooted in indigenous knowledge management practices rather than rendering the traditions of the local humanitarians and affected communities invisible.
